APP = tcpuart
PLATFORM ?= esp8266
APP_MODULES = src
APP_FS_PATH = ./fs
APP_SLFS_PATH = ./slfs
APP_CONF_SCHEMA = src/conf_schema.yaml
APP_CFLAGS = -DCS_LOG_TS_DIFF -DMG_LWIP_SSL_RECV_MBUF_LIMIT=1024
BUILD_DIR = .build-$(PLATFORM)
SJ_ENABLE_JS = 0
SJ_ENABLE_CLUBBY = 1
ifeq ("$(PLATFORM)","esp8266")
  MG_DEBUG_UART = 1
  SSL = Krypton
endif

include $(REPO_PATH)/fw/platforms/$(PLATFORM)/Makefile.build
